### ISSUE TITLE
New Test Videos

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#16]
I created four test videos:

1 Drawing: https://vimeo.com/77716815
2 Color: https://vimeo.com/77716817
3 Interaction: https://vimeo.com/77716816
4 Questions: https://vimeo.com/77716818

@scottgarner and I were discussing how a lot of the work we have to do is "data entry" work, in terms of entering in all the timecodes for the various popcorn events.  @scottgarner, would it make sense for you to put these videos into the site with some initial content and then we ( @REAS @alignedleft @shiffman ) can do some of this data entry?  Perhaps we would need a template or short set of guidelines?

Also, I expect you will all have lots of comments and suggestions for the "script" content.  Should we collect those as vimeo comments?

I did these videos off the top of my head, but it might also be useful for me to go back and create a script "outline" from them that we could collaborative edit / review.  I'll try to work on that.

**Comment by scottgarner** [comment]
Thanks, Dan! I have class shortly, but will get these in place with at least skeletal info as soon as I can and we'll see what makes sense as far as entering content.

Currently things are built for a single long video, but it shouldn't take much time to swap that out. I'm a little undecided on the best approach in the long run. One video means less buffering, but it can lead to some weird Popcorn side effects when jumping around. 

I'll see what I can learn from these videos and go from there.

**Comment by shiffman** [comment]
I'll upload one long video if you would prefer that.

**Comment by scottgarner** [comment]
I think this will actually be better because I was definitely having some issues now and then jumping backwards with Popcorn because it tries to undo all of the events it has triggered. Discrete videos will help that, but buffering could be a problem.

Anyway, I think it's a worthwhile experiment and easy enough to change back.

**Comment by REAS** [comment]
@shiffman These videos are so full of potential. I think you're doing a great keeping the jargon out. 

I'm concerned about the legibility of what you're doing on the whiteboard because the video window will be small. I think this could be improved by using a small whiteboard, like the IKEA easel in your house and the camera is in tighter or by getting fat markers. 

There's also the potential to insert typography directly on top of your images in the video so you wouldn't need to write. I'm concerned that writing while you're talking is a part of your thought process, though.  

We could also use the Bob Dylan approach of flipping cards. At the moment, I think this might be ideal. We could place them on a easel and you can point to the important points with a baton or your hand while you speak. Also, like on CSPAN. It also frees us up to shoot about anywhere.

What do you think about the card idea?

http://www.youtube.com/watch?v=VY4HtQ-XJQE

**Comment by shiffman** [comment]
@scottgarner great!  (I have one that is the 4 stitched together so just say the word if it turns out you want me to upload that to vimeo)

@REAS the drawing while I talk definitely makes me feel comfortable (it's what I do in class). . . I have also always felt (but am not sure) that it enforces a certain pacing which allows the viewer to pause and absorb while things are written out or draw.  I do like these other ideas and would gladly try them.  The cards is rather amusing and looks like fun, maybe I'll give that a quick test in my office and see how it goes.

**Comment by scottgarner** [comment]
Just some notes on this:

The idea of software-side annotations makes me worry because that's adding more features to an already rushed platform, though overlays like that could also be added in the video file itself.

In getting started setting up these new videos, I think it might make sense to pop the video back to fullscreen for long explanations that aren't explicitly referring to the code or canvas, which helps with legibility. Granted, I've only really gotten started on the first video, so that may not be practical throughout and switching back and forth too much would be distracting.

I have to say though, that after watching all of the Nature of Code and ICM videos, the though of @shiffman teaching without whiteboard antics is a little strange to me.

**Comment by REAS** [comment]
I think switching back and forth is a great idea. When you want the student to be listening closely, it's best to obscure the text editor and bring Dan full frame. That will take care of my legibility concerns. I do like the card idea, but this is entirely Dan's decision.

**Comment by shiffman** [comment]
@REAS, what style do you propose for the cards?  Do you imagine they would be similar to the whiteboard scribblings but drawn out a bit more neatly in advance?  Or some specific design aesthetic?   I would like to try to make a few and record a test next week so we can compare.

**Comment by REAS** [comment]
"Do you imagine they would be similar to the whiteboard scribblings but drawn out a bit more neatly in advance?" Yes, that's what I was thinking.

**Comment by scotthmurray** [comment]
Agreed that:
- Dan, you should just speak/write/perform using whatever format you're most comfortable with.
- Legibility is a concern, so it would be ideal if we can toggle the view between (a) the whole scene with Dan and (b) just the whiteboard.  (Same applies if you try the card concept.)

**Comment by shiffman** [comment]
videos shot!

**Comment by REAS** [comment]
Wonderful!
