### ISSUE TITLE
Architecture and Site Map

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#2]
For the underlying architecture, I've used HTML5 Boilerplate and Twitter Bootstrap to get things going. Beyond what's in the wireframes, what other pages need to be handled? Is it as simple as: 

— Landing Page
  — Video / Code Page

Or do we need things like an About page, etc.? Maybe content like that can just be popped up in the main view?

**Comment by scottgarner** [comment]
I started doing some Jekyll tempting to make things easier. The one catch is that a setup likes this works better at the top of a site than in a subdirectory. In other words, something like `hour.processing.org` versus `processing.org/hour`. 

The later is certainly possible, it just requires a few more templates to keep the paths from breaking.

**Comment by REAS** [comment]
I think we want it at the top, at the moment hello.processing.org is the favorite. I don't think we need an About page. We'll likely want a landing page and in the end we'll likely want an ending or conclusion page.

**Comment by REAS** [comment]
New idea. We should have a timeline at the top of bottom of the site so students can see where they are within the "hour" and if they get interrupted and want to come back later, they can move to anywhere within the timeline. For example, if we break this into 5 sections, if a student at at section 4, she could go back to section 2 to see Dan explain something again, then could jump back to 4 to code.

**Comment by scotthmurray** [comment]
Yes, great idea — like a progress meter.

Re: other pages, I was envisioning this as a single-page site.  All the content will fit at some step along that timeline/meter.

**Comment by scottgarner** [comment]
I think single-page works for the most part, too, though I might suggest at least two other pages for the landing/splash and for the shared content page that people would see coming in from Facebook or Twitter.

All elements of code editing and video watching will work well in a single page with the timeline for navigation.

**Comment by shiffman** [comment]
I love the timeline idea.  Would we want to have a clock that is continuously tracking the hour and automatically advance?   We could also include a "pause" button.

**Comment by REAS** [comment]
I'm not sure about the "stopwatch" but I've thought about it a few times. I've been trying to how important the "hour" is. At the moment, I'm thinking more that the hour is estimated, but not enforced. I've thought through:
1. If time is important in the classroom, the teacher in the class might say "time to move to the next step"
2. If a student only makes it half-way through in the hour because he is moving at his own pace, that might be a better experience than putting that student on the clock and generating some anxiety.

**Comment by scottgarner** [comment]
Just to drill down on the presentation of the timeline, what exactly does the user see? Something like:

[ Intro | Lesson 1 | Lesson 2 | Lesson 3 | Lesson 4 | Outro ]

And clicking any one section would take you to the video/editor display for that lesson?

**Comment by shiffman** [comment]
agree @REAS about the clock.  Perhaps there's a subtle way (without an actual countdown) that we can provide "suggested" times for a teacher who is managing a group etc.

Scott, I think this is probably the right start. I would love for us to come up with descriptive titles instead of lesson numbers.  Of course I can't think of anything great right now -- but maybe it's more like:

shapes | color | interaction | etc

**Comment by shiffman** [comment]
I think we've moved past this discussion.  Closing this issue and we can open a new one to discuss clock / hints area content when the time comes.
