### ISSUE TITLE
Share Button

### ISSUE THREAD

**Issue by scottgarner** [processing/Processing-Hour-Of-Code#23]
The current plan for the share button is to only show it after the goodbye video when you'll have the option to return to the editor.

The backend code that saves a Gist and returns a permalink is in place. Initial work on a Twitter button is in place.

I want to clean things up a bit, add some copy and finish adding links to share on FB and Google+. This will use the most barebones sharing functionality available where a new window opens to, for example, submit a tweet.

**Comment by scottgarner** [comment]
The share button should now properly share to Facebook, Google+ and Twitter using the most basic mechanisms available. I don't have a Facebook account, so I'm not 100% that it works, but the URL should at least be properly formed. I'll close this for now and make a note to test social as part of our QA process.

**Comment by shiffman** [comment]
FYI, the facebook and google+ share buttons only shared this URL for me:

http://hello.processing.org/display/

rather than:

http://hello.processing.org/display/#7419605

Twitter worked great.  Also, related issue, but should the link to http://hello.processing.org/display/#7419605 in the share area open a page in a new tab?  If you click the link you lose your place in the tutorial (which yes will be at the end, but maybe you wanted to keep going?)  Not sure if I am being clear.

**Comment by scottgarner** [comment]
Uh oh, I hope Facebook and Google+ aren't stripping the location hash. I've tried encoding the URL, which I hope will fix things. The Google+ preview page seems to work for me. Would you mind testing again?

Good catch on the link! I changed the code so it should open in a new window.

**Comment by shiffman** [comment]
yup, they both work now!
