### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by shiffman** [processing/Processing-Hour-Of-Code#29]
We should find a place to have credits on the site for everyone who has contributed to the tutorial as well as info on the open source tools we've used, link to our github repo, etc.

**Comment by scottgarner** [comment]
I have a note to link to this in the final hints. It could also be something that's always accessible, though I don't know where the button would live. I think we have three options for presenting it:
1. A separate "about" page on the site. We'd have to open it in a new tab or window so that the user didn't accidentally lose their place in the lesson.
2. As some kind of modal window or overlay within the editor page. This is doable, but might not be the nicest presentation.
3. As the Readme on the GitHub repository. Somehow this seems most "correct" to me, but is the least fancy presentation.

**Comment by REAS** [comment]
I like the idea of an "about" page that is accessible from the top menu or even About and Credits. We should emphasize credits because much of this work is volunteer. The about can explain a little about Processing and about this specific tutorial. I can be on the hook to write it. This information can be doubled in GitHub.

**Comment by scottgarner** [comment]
I created a Readme.md at the root of the repository. If you can work there in Markdown, @REAS, it will be easy to convert it to HTML for display on the site, too.

I started a partial list of tools and technologies that I can flesh out into actual text with links, etc.

**Comment by scottgarner** [comment]
@REAS, I added this to the draft milestone due this weekend if that works for you. The idea is just to get at least some rough content for every part of the site before next week.

**Comment by scottgarner** [comment]
Closing this bug to start a thread specifically for the "About" page.
